# Generated by Django 5.1.1 on 2025-03-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
