# Generated by Django 5.1.1 on 2025-03-18 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_post_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCircleFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topiccircle', verbose_name='圈子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户圈子关注',
                'verbose_name_plural': '用户圈子关注',
                'unique_together': {('user', 'circle')},
            },
        ),
    ]
