# Generated by Django 5.1.1 on 2025-03-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_usercirclefollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
