# Generated by Django 5.1.1 on 2025-03-19 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_comment_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercirclefollow',
            options={'verbose_name': 'User Circle Follow', 'verbose_name_plural': 'User Circle Follow'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(verbose_name='Announcement Content'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Whether pin'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Announcement Title'),
        ),
        migrations.AlterField(
            model_name='usercirclefollow',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topiccircle', verbose_name='Circle'),
        ),
        migrations.AlterField(
            model_name='usercirclefollow',
            name='followed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Followed At'),
        ),
        migrations.AlterField(
            model_name='usercirclefollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='GUser'),
        ),
    ]
