from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
#   path('login/', views.custom_login, name='login'),
    path('circle/<int:circle_id>/', views.circle_detail, name='circle_detail'),
    path('circle/<int:circle_id>/post/', views.create_post, name='create_post'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/<int:post_id>/like/', views.like_post, name='like_post'),
    path('post/<int:post_id>/dislike/', views.dislike_post, name='dislike_post'),
    path('post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('post/<int:post_id>/report/', views.report_post, name='report_post'),
    path('post/<int:post_id>/delete/', views.user_post_delete, name='user_post_delete'),
    path('post/<int:post_id>/admin-delete/', views.admin_post_delete, name='admin_post_delete'),
    path('post/<int:post_id>/pin/', views.pin_post, name='pin_post'),
    path('post/<int:post_id>/recommend/', views.recommend_post, name='recommend_post'),
    path('comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    path('comment/<int:comment_id>/dislike/', views.dislike_comment, name='dislike_comment'),
    path('comment/<int:comment_id>/report/', views.report_comment, name='report_comment'),
    path('comment/<int:comment_id>/delete/', views.admin_comment_delete, name='admin_comment_delete'),
    path('all-circles/', views.all_circles, name='all_circles'),
    path('profile/', views.profile, name='profile'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/circle/create/', views.circle_create, name='circle_create'),
    path('admin/circle/<int:circle_id>/edit/', views.circle_edit, name='circle_edit'),
    path('admin/circle/<int:circle_id>/delete/', views.circle_delete, name='circle_delete'),
    path('admin/report/<int:report_id>/resolve/', views.report_resolve, name='report_resolve'),
    path('admin/post/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('admin/announcement/create/', views.announcement_create, name='announcement_create'),
    path('announcement/<int:announcement_id>/', views.announcement_detail, name='announcement_detail'),
    path('admin/announcement/<int:announcement_id>/manage/', views.announcement_manage, name='announcement_manage'),
    path('search/', views.search, name='search'),
]